source "https://rubygems.org"

gem "jekyll", "~> 4.2"
gem "webrick", "~> 1.7"  # Needed for Ruby 3.0+
gem "minima", "~> 2.5"   # The minima theme

# If you want to use GitHub Pages
# gem "github-pages", group: :jekyll_plugins

# Jekyll plugins
group :jekyll_plugins do
  gem "jekyll-feed"
  gem "jekyll-seo-tag"
  gem "jekyll-sitemap"
end
