name: Deploy Jekyll site to Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies for SVG and PDF conversion
      run: |
        sudo apt-get update
        sudo apt-get install librsvg2-bin pandoc texlive-latex-base texlive-xcolor -y

    - name: Install LaTeX packages
      run: |
        sudo apt-get update
        sudo apt-get install -y texlive-latex-base texlive-latex-extra texlive-fonts-recommended texlive-xcolor texlive-fonts-extra texlive-science

    - name: Build PDF and HTML from Markdown
      run: |
        ./build.sh markdown build
        mkdir -p website/static/pdfs
        if [ -f output/bridge_neural_networks_md.pdf ]; then
          cp output/bridge_neural_networks_md.pdf website/static/pdfs/bridge_neural_networks.pdf
        else
          echo "PDF not generated, using HTML fallback."
        fi

    - name: Build Jekyll site
      run: |
        cd website
        bundle install
        bundle exec jekyll build

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: site
        path: website/_site