name: Deploy Jekyll site to Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install LaTeX packages
      run: |
        sudo apt-get update
        sudo apt-get install -y texlive-latex-base texlive-latex-extra texlive-fonts-recommended texlive-xcolor

    - name: Generate PDF
      run: |
        mkdir -p output
        pdflatex -interaction=nonstopmode -output-directory=output bridge_neural_networks.tex || exit 1

    - name: Fallback to HTML
      if: failure()
      run: echo "PDF generation failed. Using HTML version."
